apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      name: mongodb-pod
      labels:
        app: mongodb
    spec:
      volumes:
        - name: mongo-volume
          hostPath:
            path: /mongo-volume
            type: DirectoryOrCreate
      containers:
        - name: mongo
          image: mongo:latest
          volumeMounts:
            - mountPath: /data/db
              name: mongo-volume
