apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-persistent-volume
  labels:
    type: mongo-pv
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Mi
  hostPath:
    path: /mongo-volume
