apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: metadataservice-replicaset
  labels:
    app: metadataserviceapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: metadataserviceapp
  template:
    metadata:
      name: metadataservice
      labels:
        app: metadataserviceapp
    spec:
      containers:
        - name: metaservice
          image: luckyganesh/metadata-service:v1
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 3
